name: Build Android APK (Raw Gradle - Release)

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Generate Native Android Code
        run: npx expo prebuild --platform android

      - name: Build Android APK (Release)
        working-directory: android
        env:
          ORG_GRADLE_PROJECT_newArchEnabled: "true"
        run: ./gradlew app:assembleRelease -PnewArchEnabled=true --stacktrace --info

      - name: Upload APK artifact (release)
        uses: actions/upload-artifact@v4
        with:
          name: gemwallet-standalone-apk
          path: android/app/build/outputs/apk/release/*.apk
